service: diagnal-og

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
stage: dev
region: us-east-1
role: arn:aws:iam::151126869849:role/serverless_lambda_role

plugins:
  - serverless-offline
 
custom:
  serverless-offline:
    httpPort: 3000

functions:
  ServerlessOGD:
    handler: handler.parseOGD  
    events:
      - http:
          path: parse
          method: get